POST http://localhost:3006/api/user/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "pass123QWE"
}
###
POST http://localhost:3006/api/user/invite
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0Mzc4OTgwNCwiZXhwIjoxNzQzNzk3MDA0fQ.sqjFJdNYjEZuRMp1aWUI_D0wB2l8WjHZssBddQgZ48o

{
    "email": "guest2@gmail.com",
    "name" : "laura",
    "surnames" : "perez",
    "password": "abc123TG"
}

###
POST http://localhost:3006/api/client
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2YwMWYzNmMwYjdlYTQ4YmUyZGZlNzciLCJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NDM3ODk4NzksImV4cCI6MTc0Mzc5NzA3OX0.2N1Bmbw6Kkki7qIEdpzscVOZLgEmOEC-6SVtlvYQ-HA
Content-Type: application/json

{
    "name": "Cliente2 de admin",
    "cif": "123456789L",
    "address":{
        "street": "Gran Vía",
        "province": "Pontevedra",
        "number": 3,
        "postal": 36885,
        "city": "Vigo"
    }
}

###
PATCH http://localhost:3006/api/client/67f016780168f2dd53e65c53
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2YwMTY1MjAxNjhmMmRkNTNlNjVjNGQiLCJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NDM3ODc2MDIsImV4cCI6MTc0Mzc5NDgwMn0.68J02OpFGBqaGzGHAU6V3zTIlnD8rQ0J69x-ohI5c6M
Content-Type: application/json

{
    "cif": "123456789L",
    "address":{
        "street": "Calle Fuencarral",
        "province": "Pontevedra",
        "number": 10,
        "postal": 36004,
        "city": "Pontevedra"
    }
}

###
GET http://localhost:3006/api/client
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2YwMWYzNmMwYjdlYTQ4YmUyZGZlNzciLCJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NDM3ODk4NzksImV4cCI6MTc0Mzc5NzA3OX0.2N1Bmbw6Kkki7qIEdpzscVOZLgEmOEC-6SVtlvYQ-HA


###
GET http://localhost:3006/api/client/67f012155860f80af0c55999
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2YwMWYzNmMwYjdlYTQ4YmUyZGZlNzciLCJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NDM3ODk4NzksImV4cCI6MTc0Mzc5NzA3OX0.2N1Bmbw6Kkki7qIEdpzscVOZLgEmOEC-6SVtlvYQ-HA
