POST http://localhost:3006/api/user/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "pass123QWE"
}

###
POST http://localhost:3006/api/deliverynote
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDI5ODAwNCwiZXhwIjoxNzQ0MzA1MjA0fQ.1-Mnxus3owN85-ny-9BgSM-NuXIRJYMCwxiOvdEQmwQ
Content-Type: application/json

{
  "clientId": "67f012155860f80af0c55999",
  "projectId": "67f3ca25580c6b843c2ae0da",
  "format": "material",
  "materials": "paper",
  "description": "This is a realistic description",
  "workdate": "2/5/2025"
}

###
GET http://localhost:3006/api/deliverynote?company=false
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDI5ODAwNCwiZXhwIjoxNzQ0MzA1MjA0fQ.1-Mnxus3owN85-ny-9BgSM-NuXIRJYMCwxiOvdEQmwQ
###
GET http://localhost:3006/api/deliverynote?company=true
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEzMTY3MCwiZXhwIjoxNzQ0MTM4ODcwfQ.kvb-tlI8_6vt92dwQ0T7YMYNJmowh-IMLDYVH7JD_50

###
GET http://localhost:3006/api/deliverynote/67f564bdc5911f594d2dcf2d
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEzMTY3MCwiZXhwIjoxNzQ0MTM4ODcwfQ.kvb-tlI8_6vt92dwQ0T7YMYNJmowh-IMLDYVH7JD_50

###
GET http://localhost:3006/api/deliverynote/pdf/67f7e56b393b68a750bbba00
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDI5ODAwNCwiZXhwIjoxNzQ0MzA1MjA0fQ.1-Mnxus3owN85-ny-9BgSM-NuXIRJYMCwxiOvdEQmwQ

###

PATCH http://localhost:3006/api/deliverynote/sign/67f7e56b393b68a750bbba00
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDI5ODAwNCwiZXhwIjoxNzQ0MzA1MjA0fQ.1-Mnxus3owN85-ny-9BgSM-NuXIRJYMCwxiOvdEQmwQ
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="firma.png"
Content-Type: image/png

< ./firma.png
--boundary123--

###
DELETE http://localhost:3006/api/deliverynote/67f7e56b393b68a750bbba00
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDI5ODAwNCwiZXhwIjoxNzQ0MzA1MjA0fQ.1-Mnxus3owN85-ny-9BgSM-NuXIRJYMCwxiOvdEQmwQ
