POST http://localhost:3006/api/user/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "pass123QWE"
}
###
POST http://localhost:3006/api/project
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDAzMDIxOSwiZXhwIjoxNzQ0MDM3NDE5fQ.rs57tQITE3s6YvtGdoSkIAys5fQsdB_X-iy65_z1DrE

{
  "name": "Proyecto3",
  "projectCode": "003",
  "email": "mimail@gmail.com",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  },
  "code": "3",
  "clientId": "67f012155860f80af0c55999"
}

###
PUT http://localhost:3006/api/project/67f262a995d26d2d23a20a23
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0Mzk0Njg4MCwiZXhwIjoxNzQzOTU0MDgwfQ.QEEq_qobZVUHxJ5PEmUff_jD6KhGRqgu_L6dCqAsBmQ

{
  "name": "Nombre del proyecto",
  "projectCode": "Identificador de proyecto",
  "email": "mimail@gmail.com",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 36587,
    "city": "Vigo",
    "province": "Pontevedra"
  },
  "code": "Código interno del proyecto",
  "clientId": "67f012155860f80af0c55999"
}

###
GET http://localhost:3006/api/project
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDAzMDIxOSwiZXhwIjoxNzQ0MDM3NDE5fQ.rs57tQITE3s6YvtGdoSkIAys5fQsdB_X-iy65_z1DrE

###
GET http://localhost:3006/api/project/67f3ca25580c6b843c2ae0da
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDAzMDIxOSwiZXhwIjoxNzQ0MDM3NDE5fQ.rs57tQITE3s6YvtGdoSkIAys5fQsdB_X-iy65_z1DrE

###
DELETE http://localhost:3006/api/project/67f3ca25580c6b843c2ae0da
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDAzMDIxOSwiZXhwIjoxNzQ0MDM3NDE5fQ.rs57tQITE3s6YvtGdoSkIAys5fQsdB_X-iy65_z1DrE

###
DELETE http://localhost:3006/api/project/archive/67f3ca25580c6b843c2ae0da
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDAzMDIxOSwiZXhwIjoxNzQ0MDM3NDE5fQ.rs57tQITE3s6YvtGdoSkIAys5fQsdB_X-iy65_z1DrE

###
GET http://localhost:3006/api/project/archive
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDAzMDIxOSwiZXhwIjoxNzQ0MDM3NDE5fQ.rs57tQITE3s6YvtGdoSkIAys5fQsdB_X-iy65_z1DrE

###
PATCH  http://localhost:3006/api/project/archive/67f3ca25580c6b843c2ae0da
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDAzMDIxOSwiZXhwIjoxNzQ0MDM3NDE5fQ.rs57tQITE3s6YvtGdoSkIAys5fQsdB_X-iy65_z1DrE
