POST http://localhost:3006/api/user/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "pass123QWE"
}
###
POST http://localhost:3006/api/project
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyNzQyMiwiZXhwIjoxNzQ0MTM0NjIyfQ.xwL9dh0HIzzmggX5Pd2KGsFqDe9z8-MJnA0NPV5lML4

{
  "name": "Proyecto4",
  "projectCode": "004",
  "email": "mimail@gmail.com",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  },
  "code": "3",
  "clientId": "67f012155860f80af0c55999"
}

###
PUT http://localhost:3006/api/project/67f54623215a24688ca610a4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyNzQyMiwiZXhwIjoxNzQ0MTM0NjIyfQ.xwL9dh0HIzzmggX5Pd2KGsFqDe9z8-MJnA0NPV5lML4

{
  "name": "Proyecto4",
  "projectCode": "004",
  "email": "mimail@gmail.com",
  "address": {
    "street": "Carlos V",
    "number": 922,
    "postal": 36587,
    "city": "Vigo",
    "province": "Pontevedra"
  },
  "code": "Código interno del proyecto",
  "clientId": "67f012155860f80af0c55999"
}

###
GET http://localhost:3006/api/project
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyNzQyMiwiZXhwIjoxNzQ0MTM0NjIyfQ.xwL9dh0HIzzmggX5Pd2KGsFqDe9z8-MJnA0NPV5lML4

###
GET http://localhost:3006/api/project/67f3ca25580c6b843c2ae0da
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyNzQyMiwiZXhwIjoxNzQ0MTM0NjIyfQ.xwL9dh0HIzzmggX5Pd2KGsFqDe9z8-MJnA0NPV5lML4

###
DELETE http://localhost:3006/api/project/67f3ca25580c6b843c2ae0da
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyNzQyMiwiZXhwIjoxNzQ0MTM0NjIyfQ.xwL9dh0HIzzmggX5Pd2KGsFqDe9z8-MJnA0NPV5lML4

###
DELETE http://localhost:3006/api/project/archive/67f3ca25580c6b843c2ae0da
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyNzQyMiwiZXhwIjoxNzQ0MTM0NjIyfQ.xwL9dh0HIzzmggX5Pd2KGsFqDe9z8-MJnA0NPV5lML4

###
GET http://localhost:3006/api/project/archive
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyNzQyMiwiZXhwIjoxNzQ0MTM0NjIyfQ.xwL9dh0HIzzmggX5Pd2KGsFqDe9z8-MJnA0NPV5lML4

###
PATCH  http://localhost:3006/api/project/archive/67f3ca25580c6b843c2ae0da
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3YmQzY2NhMjRiYTg2NDdhZjIyN2QiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyNzQyMiwiZXhwIjoxNzQ0MTM0NjIyfQ.xwL9dh0HIzzmggX5Pd2KGsFqDe9z8-MJnA0NPV5lML4
